# Generated by Django 4.0.3 on 2022-12-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='상품가격')),
                ('qty', models.IntegerField(verbose_name='상품수량')),
                ('create_date', models.DateTimeField(verbose_name='생성일시')),
            ],
        ),
    ]
